In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import  TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
pip install summarytools

Note: you may need to restart the kernel to use updated packages.


In [3]:
from summarytools import dfSummary

In [4]:
df = pd.read_csv(r"C:\Users\TECH POINT\Desktop\Book Recommender\data.csv")
df

isbn13      isbn10                      title  \
0     9780002005883  0002005883                     Gilead   
1     9780002261982  0002261987               Spider's Web   
2     9780006163831  0006163831               The One Tree   
3     9780006178736  0006178731             Rage of angels   
4     9780006280897  0006280897             The Four Loves   
...             ...         ...                        ...   
6805  9788185300535  8185300534                  I Am that   
6806  9788185944609  8185944601       Secrets Of The Heart   
6807  9788445074879  8445074873             Fahrenheit 451   
6808  9789027712059  9027712050   The Berlin Phenomenology   
6809  9789042003408  9042003405  'I'm Telling You Stories'   

                                            subtitle  \
0                                                NaN   
1                                            A Novel   
2                                                NaN   
3                                                NaN   
4                                                NaN   
...                                              ...   
6805             Talks with Sri Nisargadatta Maharaj   
6806                                             NaN   
6807                                             NaN   
6808                                             NaN   
6809  Jeanette Winterson and the Politics of Reading   

                                           authors  \
0                               Marilynne Robinson   
1                  Charles Osborne;Agatha Christie   
2                             Stephen R. Donaldson   
3                                   Sidney Sheldon   
4                              Clive Staples Lewis   
...                                            ...   
6805  Sri Nisargadatta Maharaj;Sudhakar S. Dikshit   
6806                                 Khalil Gibran   
6807                                  Ray Bradbury   
6808                 Georg Wilhelm Friedrich Hegel   
6809                        Helena Grice;Tim Woods   

                         categories  \
0                           Fiction   
1     Detective and mystery stories   
2                  American fiction   
3                           Fiction   
4                    Christian life   
...                             ...   
6805                     Philosophy   
6806                      Mysticism   
6807                   Book burning   
6808                        History   
6809             Literary Criticism   

                                              thumbnail  \
0     http://books.google.com/books/content?id=KQZCP...   
1     http://books.google.com/books/content?id=gA5GP...   
2     http://books.google.com/books/content?id=OmQaw...   
3     http://books.google.com/books/content?id=FKo2T...   
4     http://books.google.com/books/content?id=XhQ5X...   
...                                                 ...   
6805  http://books.google.com/books/content?id=Fv_JP...   
6806  http://books.google.com/books/content?id=XcrVp...   
6807                                                NaN   
6808  http://books.google.com/books/content?id=Vy7Sk...   
6809  http://books.google.com/books/content?id=2lVyR...   

                                            description  published_year  \
0     A NOVEL THAT READERS and critics have been eag...          2004.0   
1     A new 'Christie for Christmas' -- a full-lengt...          2000.0   
2     Volume Two of Stephen Donaldson's acclaimed se...          1982.0   
3     A memorable, mesmerizing heroine Jennifer -- b...          1993.0   
4     Lewis' work on the nature of love divides love...          2002.0   
...                                                 ...             ...   
6805  This collection of the timeless teachings of o...          1999.0   
6806                                                NaN          1993.0   
6807                                                NaN          2004.0   
6808  Since the th

In [5]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [6]:
dfSummary(df)

In [7]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   isbn13          6810 non-null   int64  
 1   isbn10          6810 non-null   object 
 2   title           6810 non-null   object 
 3   subtitle        2381 non-null   object 
 4   authors         6738 non-null   object 
 5   categories      6711 non-null   object 
 6   thumbnail       6481 non-null   object 
 7   description     6548 non-null   object 
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB


In [8]:
selected_features = ['title', 'authors', 'categories', 'published_year']
print(selected_features)

['title', 'authors', 'categories', 'published_year']


In [9]:
df.duplicated().sum()

0

In [10]:
for feature in selected_features:
    df[feature] = df[feature].fillna('')

In [11]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors              0
categories           0
thumbnail          329
description        262
published_year       0
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [12]:
combined_features = df['title'] + ' ' + df['categories'] + ' ' + df['authors'] + ' ' + f"{df['published_year']}"
#  The f-string converts the value of df['published_year'] into a string, making it compatible with the concatenation.
combined_features

0       Gilead Fiction Marilynne Robinson 0       2004...
1       Spider's Web Detective and mystery stories Cha...
2       The One Tree American fiction Stephen R. Donal...
3       Rage of angels Fiction Sidney Sheldon 0       ...
4       The Four Loves Christian life Clive Staples Le...
                              ...                        
6805    I Am that Philosophy Sri Nisargadatta Maharaj;...
6806    Secrets Of The Heart Mysticism Khalil Gibran 0...
6807    Fahrenheit 451 Book burning Ray Bradbury 0    ...
6808    The Berlin Phenomenology History Georg Wilhelm...
6809    'I'm Telling You Stories' Literary Criticism H...
Length: 6810, dtype: object

In [13]:
vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(combined_features)

In [14]:
print(feature_vectors)

  (0, 6894)	0.06443750710614472
  (0, 2840)	0.06443750710614472
  (0, 143)	0.06443750710614472
  (0, 5557)	0.06443750710614472
  (0, 7629)	0.06443750710614472
  (0, 6655)	0.06443750710614472
  (0, 102)	0.06443750710614472
  (0, 142)	0.06443750710614472
  (0, 91)	0.06443750710614472
  (0, 141)	0.06443750710614472
  (0, 140)	0.06443750710614472
  (0, 139)	0.06443750710614472
  (0, 103)	0.06443750710614472
  (0, 138)	0.06443750710614472
  (0, 110)	0.06443750710614472
  (0, 98)	0.12887501421228945
  (0, 92)	0.06443750710614472
  (0, 108)	0.06443750710614472
  (0, 112)	0.12887501421228945
  (0, 8035)	0.43700046813706117
  (0, 6013)	0.5885172279797457
  (0, 3422)	0.11189605685054443
  (0, 3882)	0.5885172279797457
  (1, 1822)	0.3013956698681646
  (1, 267)	0.30498953565603815
  :	:
  (6809, 10330)	0.33175135989257093
  (6809, 2240)	0.2206043839379868
  (6809, 9492)	0.30218650531542857
  (6809, 10435)	0.26439634843355025
  (6809, 5684)	0.20438577371569946
  (6809, 9065)	0.21319651041165227
  (6

In [15]:
similarity = cosine_similarity(feature_vectors, feature_vectors)

In [16]:
print(similarity)

[[1.         0.08005311 0.11641123 ... 0.08492469 0.08320896 0.07576596]
 [0.08005311 1.         0.08011208 ... 0.06549297 0.06416982 0.10645452]
 [0.11641123 0.08011208 1.         ... 0.08498725 0.09570742 0.07582177]
 ...
 [0.08492469 0.06549297 0.08498725 ... 1.         0.06807484 0.06198557]
 [0.08320896 0.06416982 0.09570742 ... 0.06807484 1.         0.06073329]
 [0.07576596 0.10645452 0.07582177 ... 0.06198557 0.06073329 1.        ]]


In [24]:
list_of_all_titles = df['title'].tolist()
book_name =  'Tell Me Your Dreams'
# finding the close match for the book name given by the user
find_close_match = difflib.get_close_matches(book_name, list_of_all_titles)
print(find_close_match)

['Tell Me Your Dreams', 'Tell Me No Lies', 'Tell My Horse']


In [25]:
import joblib

joblib.dump(similarity, "Books_recommender.pkl")

['Books_recommender.pkl']

In [26]:
# finding the index of the book with title 
close_match = find_close_match[0]
index_of_the_book = df[df.title==close_match].index[0]


In [28]:
# getting a list of similar books
similarity_score = list(enumerate(similarity[index_of_the_book]))
print(similarity_score)

[(0, 0.09861621275296131), (1, 0.06786587649043539), (2, 0.09868886100290314), (3, 0.46438838269728794), (4, 0.0726343039980105), (5, 0.06755909068703153), (6, 0.0902494564276177), (7, 0.0679174213479147), (8, 0.05804538013554027), (9, 0.42536062088472276), (10, 0.3825291153824308), (11, 0.08715420464700939), (12, 0.08533903156975484), (13, 0.060234812137786045), (14, 0.06332339555694128), (15, 0.08312684480774048), (16, 0.0764560573292661), (17, 0.0653152545318414), (18, 0.0829362281829355), (19, 0.08525509946147161), (20, 0.08460917919561367), (21, 0.07248498318500983), (22, 0.08574659817800029), (23, 0.06436184237933433), (24, 0.07352941031439593), (25, 0.07078338294349529), (26, 0.06665001914055306), (27, 0.06942319382037827), (28, 0.10106028553831384), (29, 0.07501196532618584), (30, 0.06953983439267682), (31, 0.07338687763807245), (32, 0.07453438222113415), (33, 0.06588808877533876), (34, 0.08047035797336191), (35, 0.07360451229071337), (36, 0.06481286997809198), (37, 0.067014462

In [29]:
# sorting the books based on their similarity score
sorted_similar_books = sorted(similarity_score, key=lambda x:x[1], reverse=True)
print(sorted_similar_books)

[(2885, 1.0000000000000002), (3, 0.46438838269728794), (2891, 0.4505033114085349), (9, 0.42536062088472276), (2858, 0.4147353812598625), (1999, 0.40498825847656866), (10, 0.3825291153824308), (2077, 0.3270875051655347), (918, 0.27378623846875744), (6314, 0.27218382102414057), (4673, 0.2714312571924346), (5198, 0.27052600747232025), (5763, 0.26379683744381893), (328, 0.26379464856681156), (4342, 0.26377756260822666), (4850, 0.2551764397626548), (6804, 0.2507287075885585), (3684, 0.2506866719115975), (2158, 0.24794344388868245), (3020, 0.24270689510147042), (4672, 0.2301243970725526), (4717, 0.22791997532871458), (6575, 0.22627963404550286), (3615, 0.22530097704809726), (1518, 0.2187821399561882), (3816, 0.21283014890584057), (6791, 0.20896066175198638), (2724, 0.20842321253346519), (3000, 0.20837080685035314), (6161, 0.20782386762391278), (2257, 0.20323922464211194), (4089, 0.202873249375267), (4678, 0.2016371878196508), (5766, 0.201071734568242), (2630, 0.201003922739637), (1434, 0.199

In [30]:
top_sim = sorted_similar_books[:5]
top_sim

[(2885, 1.0000000000000002),
 (3, 0.46438838269728794),
 (2891, 0.4505033114085349),
 (9, 0.42536062088472276),
 (2858, 0.4147353812598625)]

In [31]:
# print the name of similar books based on the index
i = 1

for book in sorted_similar_books:
    index = book[0]
    title_from_index = df[df.index==index]['title'].values[0]
    if(i<6):
        print(i, '-', title_from_index)
        i+=1

1 - Tell Me Your Dreams
2 - Rage of angels
3 - The Sky Is Falling
4 - Master of the Game
5 - Nothing Lasts Forever


In [34]:
# book_name = input('Enter your favourite book name: ')

book_name = 'Master of the Game'

list_of_all_titles = df['title'].tolist()

find_close_match = difflib.get_close_matches(book_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_book = df[df.title == close_match].index[0]

similarity_score = list(enumerate(similarity[index_of_the_book]))

sorted_similar_books = sorted(similarity_score, key = lambda x:x[1], reverse=True)

print('Books suggested for you: \n')

i = 1

for book in sorted_similar_books:
    index = book[0]
    title_from_index = df[df.index==index]['title'].values[0]
    if(i<=10):
        print(i, '.', title_from_index)
        i+=1

Books suggested for you: 

1 . Master of the Game
2 . If Tomorrow Comes
3 . Rage of angels
4 . The Sky Is Falling
5 . Tell Me Your Dreams
6 . Nothing Lasts Forever
7 . The Game
8 . Master of the Night
9 . Master of the Moon
10 . A Man Betrayed
